DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT NOT NULL,
    NAME TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    UNIQUE(USERNAME)
);

INSERT INTO Users (USERNAME, NAME, PASSWORD, EMAIL)
VALUES ('msaedi', 'Mehdi Saedi', 'password', 'msaedi@berkeley.edu');

